import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--bg-color-primary)',
        'bg-secondary': 'var(--bg-color-secondary)',
        important: 'var(--important)',
        sub: 'var(--sub)',
        body: 'var(--body)',
        'portfolio-border': 'var(--border)',
        'border-dark': 'var(--border-dark)',
        'brand-pink': '#ff5e99',
      },
      fontFamily: {
        sans: ['"Be Vietnam Pro"', 'sans-serif'],
      },
      spacing: {
        nano: '0.5rem',
        micro: '1rem',
        xsmall: '1.5rem',
        small: '2rem',
        medium: '2.5rem',
        large: '3rem',
        xlarge: '6rem',
        huge: '12rem',
      },
      screens: {
        'max-1375': { max: '1375px' },
        'max-1285': { max: '1285px' },
        'max-1275': { max: '1275px' },
        'max-1200': { max: '1200px' },
        'max-1185': { max: '1185px' },
        'max-1100': { max: '1100px' },
        'max-1045': { max: '1045px' },
        'max-1040': { max: '1040px' },
        'max-1032': { max: '1032px' },
        'max-985': { max: '985px' },
        'max-885': { max: '885px' },
        'max-875': { max: '875px' },
        'max-845': { max: '845px' },
        'max-810': { max: '810px' },
        'max-700': { max: '700px' },
        'max-675': { max: '675px' },
        'max-650': { max: '650px' },
        'max-645': { max: '645px' },
        'max-575': { max: '575px' },
        'max-545': { max: '545px' },
        'max-485': { max: '485px' },
        'max-400': { max: '400px' },
        'max-340': { max: '340px' },
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      transitionTimingFunction: {
        'brand-easing': 'cubic-bezier(0.86, 0, 0.07, 1)',
        'spring-switch': 'cubic-bezier(0.45, 0.05, 0.22, 1.3)',
        'smooth-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'logo-curve': 'cubic-bezier(0.25, 1, 0.5, 1)',
      },
      keyframes: {
        'slide-up': {
          from: { transform: 'translateY(45px)', opacity: '0' },
          to: { transform: 'none', opacity: '1' },
        },
        blink: {
          '100%': { opacity: '0' },
        },
      },
      animation: {
        'slide-up': 'slide-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) both',
        blink: 'blink 550ms alternate infinite cubic-bezier(0.86, 0, 0.07, 1)',
      },
    },
  },
  plugins: [],
} satisfies Config
